### PR TITLE
Feat/hypercore v10 compat

### PR DESCRIPTION
**Pull request by utanapishtim4storyboard**
closes [sessioncore#15](https://github.com/Storyboard-fm/sessioncore/issues/15)

## TODO
- [x] implement random-access-storage interface up to `suspend`
- [x] legacy tests passing
- [x] new tests for added random-access-storage methods passing
- [x] test with hypercore v10 in browser
- [x] test with sessioncore

### CODE REVIEW

**Review by agrathwohl — CHANGES_REQUESTED** [review]
This is super exciting!

In order to successfully test the changes, I first had to do `npm i compact-encoding`.

**Comment by utanapishtim4storyboard** [comment]
> This is super exciting!
> 
> In order to successfully test the changes, I first had to do `npm i compact-encoding`.

Thanks for the callout, fixed!

**Review by agrathwohl — APPROVED** [review]

**Review by agrathwohl — CHANGES_REQUESTED** [review]
Before we merge and cut a new release, let's update the README.md to match the updated API and implementation details.

Great work @utanapishtim4storyboard!

**Comment by utanapishtim4storyboard** [comment]
@agrathwohl just merged in my in progress changes, we'll need to rename the package if we want to open a PR with `random-access-idb` upstream but you can currently install with `npm install @storyboard-fm/stochastic-access-idb`

**Pull request closed without merging**
